### PR TITLE
[WIP] representing R list as julia Vector{Any}

### PR DESCRIPTION
**Pull request by phaverty**
This PR alters R_Julia_MD to return Vector{Any} when given an R list (VECSXP).  To make doing so simpler, it also moves the association the new R_Julia_MD array with a julia global symbol to the R_Julia function.  This is nice because it allows other functions to call R_Julia_MD without creating and destroying temporary global symbols (like in list or DataFrame creation).

I added tests to the roundtrip tests to check lists too. ~~These tests currently break because the j2r side of this is not yet implemented.~~

I'd be interested to know if you like this idea of moving the jl_set_global operation out of R_Julia_MD.

I have added return of Vector{Any} as VECSXP.

In a bigger change, I have centralized all of the R array creation to one function and handled the difference between return vectors and arrays there rather than stripping the dims off of 1D arrays later in R.

There are probably a few special types that are not doing the right thing in my code. For example, I just handle int64 as REALSXP rather than trying to see if it will fit in INTSXP (int32).

### CODE REVIEW

**Comment by armgong** [comment]
will try this in weekend ,a big thanks

**Comment by phaverty** [comment]
Have you had a chance to look a this? I think I'm still missing a few things for the more exotic julia types, but I wanted to pause and get your input before proceeding.

**Comment by armgong** [comment]
sorry for late, on  vacation  these days , I will see this in this weekend.

**Comment by armgong** [comment]
and I think we also need  test on julia 0.5 branch, it now in RC.

**Comment by phaverty** [comment]
​Great, thanks!

Pete

____________________
Peter M. Haverty, Ph.D.
Genentech, Inc.
phaverty@gene.com

**Comment by phaverty** [comment]
Yes, good point. I'll give 0.5 a try.

Pete

____________________
Peter M. Haverty, Ph.D.
Genentech, Inc.
phaverty@gene.com

**Pull request merged**
